#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPS

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enables/default
service nginx restart
